version: "3"
services:
  frontend:
    build:
      context: ./client  # Correct build context
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://18.191.252.100:5000
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}  # Reference the variable from the .env file
    volumes:
      - ./server:/usr/src/app
