version: "3"
services:
  frontend:
    build:
      context: ./client  # Correct build context
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://18.191.252.100:5000
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend



  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://jesuisdolfin:@Dolfino1@fitnesslog-cluster.wjecv1t.mongodb.net/?retryWrites=true&w=majority&appName=fitnesslog-cluster
    volumes:
      - ./server:/usr/src/app
    # Removed the `depends_on: - mongo` line because you're not using a mongo container
