name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/FitnessLog  # Change to your project directory

            # Create or update the .env file with sensitive information
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

            # Pull the latest code
            git pull origin master

            # Stop running containers (if applicable)
            docker-compose down

            # Rebuild and start containers
            docker-compose up --build -d
          EOF
